### ISSUE TITLE
invoking dbus `org.fcitx.Fcitx5` call inside lua addon will block the whole fcitx5 process

### ISSUE THREAD

**Issue by haolian9** [fcitx/fcitx5-lua#13]
first, thanks for making this awesome project, it made my life easier!

i was working on automaticaly setting rime's ascii mode to true, when i pressed <esc>, and i encountered the following problem which i think it is worth to report.

my env:

* fcitx5
* fcitx5-rime
* fcitx5-lua

lua that reproduces the problem:

```
# .local/share/fcitx5/lua/my-ugly-addon/main.lua
local fcitx = require('fcitx')

fcitx.watchEvent(fcitx.EventType.KeyEvent, 'handler')

function handler(sym, state, release)
  --- it seems `return false` mean `un-handled`

  local curim = fcitx.currentInputMethod()
  if curim ~= "rime" then
    return false
  end

  local file = io.popen([[busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 GetAsciiMode]], 'r')
  local output = file:read('*all')
  file:close()
  fcitx.log("current ascii mode of rime:")
  fcitx.log(output)

  return false
end
```

the dbus service is special which is provided by fcitx5 itself; do you think the blocking in here is a expected behavior?

**Comment by wengxt** [comment]
Well definitely expected.. you're executing code running within fcitx main thread and waiting for dbus reply that gonna be handled on fcitx main thread, which would simply cause dead lock. You should either make that command async, or you may want to find some other way to interact with another addon from lua.
