### ISSUE TITLE
ime.register_trigger 函数不触发 handleQuickPhrase

### ISSUE THREAD

**Issue by GoodbyeNJN** [fcitx/fcitx5-lua#19]
参考 [此处](https://github.com/fcitx/fcitx5-chinese-addons/blob/master/im/pinyin/pinyin.lua#L492) 代码，修改为
```lua
ime.register_trigger("pinyin_get_current_time", "显示时间", {'test'}, {'时间'})
```
本地测试发现输入 `test` 时，候选项中不显示时间，但输入 `sj` 且候选项中存在 `时间` 时，正常显示

排查逻辑找到这两处代码：
[ime.register_trigger](https://github.com/fcitx/fcitx5-lua/blob/master/src/imeapi/imeapi.lua#L164)
[registerQuickPhrase](https://github.com/fcitx/fcitx5-lua/blob/master/src/imeapi/imeapi.lua#L130)
按逻辑，最终应该触发 [handleQuickPhrase](https://github.com/fcitx/fcitx5-lua/blob/master/src/imeapi/imeapi.lua#L87) 函数，但似乎并没有被调用，反而是每次都会触发 [candidateTrigger](https://github.com/fcitx/fcitx5-lua/blob/master/src/imeapi/imeapi.lua#L108) 函数

疑惑点：
1. `handleQuickPhrase` 是否正常调用；
2. `candidateTrigger` 的调用方是哪里，什么逻辑下会被调用？

**Comment by rocka** [comment]
1. `ime.register_trigger` 的第三个参数 `input_trigger_strings` 只对 quickphrase 有意义，就是说只有进入 QuickPhrase 模式之后再输入 `test`，才能触发。比如这样写：

```lua
function test_trigger()
    return {"测试"}
end

ime.register_trigger("test_trigger", "测试", {'test'}, {})
```

结果是这样：

![image](https://user-images.githubusercontent.com/13914967/186386169-fd64d029-dd96-4801-b363-e6c7cc3b3d23.png)

2. 

> 本地测试发现输入 test 时，候选项中不显示时间，但输入 sj 且候选项中存在 时间 时，正常显示

在这里起作用的是第四个参数 `candidate_trigger_strings` ，在拼音输入法中只要候选项包含 `时间` 这个词，就能触发，调用的地方在 fcitx5-chinese-addons 的 pinyin engine 里：

https://github.com/fcitx/fcitx5-chinese-addons/blob/5.0.14/im/pinyin/pinyin.cpp#L570-L583

**Comment by rocka** [comment]
我认为应该是没有的，即便用 `fcitx.watchEvent()` 监听 UpdatePreedit 事件，取到的也只能是 engine 处理完 keyEvent 之后产生的 preedit 更新，就是界面上显示的 `te s t` 。 engine 并不是把输入的字符串解析成拼音，而是直接处理按键事件（包括字母键，数字键，符号键，控制按键等），所以并不存在“原始输入字符串”这种东西。

除非直接监听 KeyEvent ，然后自己维护一个 buffer ，但这样需要处理的情形就太多了。

**Comment by wengxt** [comment]
> 感谢答疑，另外还有个问题： ![2022-08-25_02-08](https://user-images.githubusercontent.com/6856639/186509296-9beb7898-6509-417b-a2fd-0db66775aa85.png) 拼音/双拼下输入时，有没有方法获取到原始输入字符串 `test`？ （既不是带空格的 `te s t`，也不是尝试解析为完整拼音后的 `te shu tai`）

目前没有

**Comment by wengxt** [comment]
> 我认为应该是没有的，即便用 `fcitx.watchEvent()` 监听 UpdatePreedit 事件，取到的也只能是 engine 处理完 keyEvent 之后产生的 preedit 更新，就是界面上显示的 `te s t` 。 engine 并不是把输入的字符串解析成拼音，而是直接处理按键事件（包括字母键，数字键，符号键，控制按键等），所以并不存在“原始输入字符串”这种东西。
> 
> 除非直接监听 KeyEvent ，然后自己维护一个 buffer ，但这样需要处理的情形就太多了。

fcitx4 有一个 raw input buffer 给别人读，可以给 fcitx5 添加一个类似的让 engine 提供

**Comment by yaocccc** [comment]
> 后来搜索到 [fcitx/fcitx5#270](https://github.com/fcitx/fcitx5/issues/270) ，我原先的目的与这个 issue 一致，大致就是在双拼模式之上再附加一套码表模式，且码表候选优先级高于双拼候选。 既然现阶段无法实现的话，我先关闭 issue 吧，后续功能迭代我再关注下

是的，我的目的确实就是这个，最终我使用rime实现了自己的需求。你可以参考一下我rime的配置。

**Comment by yaocccc** [comment]
> 后来搜索到 [fcitx/fcitx5#270](https://github.com/fcitx/fcitx5/issues/270) ，我原先的目的与这个 issue 一致，大致就是在双拼模式之上再附加一套码表模式，且码表候选优先级高于双拼候选。 既然现阶段无法实现的话，我先关闭 issue 吧，后续功能迭代我再关注下

https://github.com/yaocccc/rime
